version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      patch-updates:
        update-types:
          - patch
        applies-to: version-updates
      minor-updates:
        update-types:
          - minor
        applies-to: version-updates

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
