import { TwitchCommand } from "../types/command.js";
import { ping } from "./ping.js";
import { reloadCommands } from "./reloadCommands.js";
import { command } from "./command.js";
import { uptime } from "./uptime.js";
import { accountage } from "./accountage.js";
import { bot } from "./bot.js";
import { queue } from "./queue.js";
import { filesay } from "./filesay.js";
import { commandsPage } from "./commands.js";
import { title } from "./title.js";
import { game } from "./game.js";
import { followage } from "./followage.js";
import { shoutout } from "./shoutout.js";
import { quote } from "./quote.js";
import { counter } from "./counter.js";
import { permit } from "./permit.js";
import { nuke } from "./nuke.js";
import { vanish } from "./vanish.js";
import { clip } from "./clip.js";
import { sr } from "./sr.js";

export const commands = new Map<string, TwitchCommand>();

commands.set(ping.name, ping);
commands.set(reloadCommands.name, reloadCommands);
commands.set(command.name, command);
commands.set(uptime.name, uptime);
commands.set(accountage.name, accountage);
commands.set("accage", accountage);
commands.set("created", accountage);
commands.set(bot.name, bot);
commands.set(queue.name, queue);
commands.set(filesay.name, filesay);
commands.set(commandsPage.name, commandsPage);
commands.set(title.name, title);
commands.set(game.name, game);
commands.set(followage.name, followage);
commands.set(shoutout.name, shoutout);
commands.set("so", shoutout);
commands.set(quote.name, quote);
commands.set(counter.name, counter);
commands.set(permit.name, permit);
commands.set(nuke.name, nuke);
commands.set(vanish.name, vanish);
commands.set(clip.name, clip);
commands.set(sr.name, sr);
commands.set("songrequest", sr);
commands.set("song", sr);
